// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aozyrrolbhhpgkgamucb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvenlycm9sYmhocGdrZ2FtdWNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0Mjk0MzYsImV4cCI6MjA2NjAwNTQzNn0.arzLKCADfAtT-ih8-g42iNM9Vr-W4eGJ0ymzSqBwnC8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);